### ISSUE TITLE
No video on private channels

### ISSUE THREAD

**Issue by cbrst** [flubshi/pvr.waipu#82]
I'm not getting any video on some private channels, just audio.

Public channels work flawlessly.

The plugin is built from source from the Leia branch on my RPi3. Widevine is freshly installed through the plugin configuration.

**Environment:**
 - Kodi version: 18
 - OS: OSMC
 - pvr.waipu version 0.2.3
 - inputstream.adaptive version 2.4.5

Log after starting the stream:

```
2020-11-24 22:26:17.972 T:1916318320  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.waipu_92146.pvr
2020-11-24 22:26:17.974 T:1294979296  NOTICE: Creating InputStream
2020-11-24 22:26:18.635 T:1625260256 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.skin.helper.service/resources/lib/kodi_monitor.py", line 72, in onNotification
                                                self.monitor_livetv()
                                              File "/home/osmc/.kodi/addons/script.skin.helper.service/resources/lib/kodi_monitor.py", line 286, in monitor_livetv
                                                pvrart = self.metadatautils.get_pvr_artwork(li_title, li_channel, li_genre)
                                              File "/home/osmc/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 164, in get_pvr_artwork
                                                title, channel, genre, manual_select=manual_select, ignore_cache=ignore_cache)
                                              File "/home/osmc/.kodi/addons/script.module.metadatautils/lib/helpers/pvrartwork.py", line 131, in get_pvr_artwork
                                                tvdb_match = self.lookup_tvdb(searchtitle, channel, manual_select=manual_select)
                                              File "/home/osmc/.kodi/addons/script.module.metadatautils/lib/helpers/pvrartwork.py", line 392, in lookup_tvdb
                                                if item["overview"]:
                                            KeyError: 'overview'
2020-11-24 22:26:18.635 T:1625260256   ERROR: Skin Helper Service --> Exception in resources.lib.kodi_monitor ! --> 'overview'
2020-11-24 22:26:22.542 T:1294979296  NOTICE: Creating Demuxer
2020-11-24 22:26:22.543 T:1294979296  NOTICE: Opening stream: 1001 source: 256
2020-11-24 22:26:22.601 T:1294979296  NOTICE: Creating video codec with codec id: 27
2020-11-24 22:26:22.623 T:1294979296  NOTICE: Creating video thread
2020-11-24 22:26:22.625 T:1107271904  NOTICE: running thread: video_thread
2020-11-24 22:26:22.721 T:1294979296  NOTICE: Opening stream: 1002 source: 256
2020-11-24 22:26:22.748 T:1294979296  NOTICE: Finding audio codec for: 86018
2020-11-24 22:26:22.752 T:1294979296  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-11-24 22:26:22.753 T:1294979296  NOTICE: Creating audio thread
2020-11-24 22:26:22.754 T:1183432928  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-11-24 22:26:23.339 T:1183432928  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-11-24 22:26:23.346 T:1183432928  NOTICE: Previous line repeats 1 times.
2020-11-24 22:26:23.346 T:1183432928  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2020-11-24 22:26:24.510 T:1107271904 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

**Comment by cbrst** [comment]
I decided to try again after changing to a different skin, and for whatever reason, it works now.

I'm marking this as closed.
