### ISSUE TITLE
Error Contents: HTTPSConnectionPool: Max retries exceeded

### ISSUE THREAD

**Issue by volker-raschek** [flubshi/pvr.waipu#83]
**Describe the bug**

Hello folks,
when I want to open a channel like ARD, ZDF or another one I get an error, that it was not possible to open the channel and I should take a look into the log files. But I can't do anything with the logfiles and so I report directly to you to help me with my error or to fix the application (plugin).

**Environment / Umgebung:**
 - Kodi version: 18  
 - OS: LibreELEC 9.2.6
- Kodi: v18.9 Leia
 - pvr.waipu version 0.3.4
 - inputstream.adaptive version: 2.4.6.1

**Log**

```txt
2020-12-02 16:04:00.387 T:2790208368   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - unable to connect to 127.0.0.1:9982
2020-12-02 16:04:36.673 T:3011661840   ERROR: Previous line repeats 3 times.
2020-12-02 16:04:36.674 T:3011661840   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-12-02 16:04:40.389 T:2790208368   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - unable to connect to 127.0.0.1:9982
2020-12-02 16:04:47.616 T:2862306160   ERROR: EXCEPTION: Invalid setting type
2020-12-02 16:04:47.617 T:2862306160  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2020-12-02 01:21
2020-12-02 16:04:48.200 T:2862306160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPSConnectionPool(host='playout-url-provider.waipu.tv', port=443): Max retries exceeded with url: /api/channels/ARD (Caused by NewConnectionError('<urllib3.connection.VerifiedHT
TPSConnection object at 0x95bb8df0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.waipu.tv/main.py", line 10, in <module>
                                                waipu.run()
                                              File "/storage/.kodi/addons/plugin.video.waipu.tv/lib/waipu.py", line 530, in run
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.waipu.tv/lib/waipu.py", line 357, in play_channel
                                                channel = w.playChannel(playouturl)
                                              File "/storage/.kodi/addons/plugin.video.waipu.tv/lib/waipu_api.py", line 207, in playChannel
                                                r = requests.get(playouturl, data=payload, headers=headers)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPSConnectionPool(host='playout-url-provider.waipu.tv', port=443): Max retries exceeded with url: /api/channels/ARD (Caused by NewConnectionError('<urllib3.connection.VerifiedH
TTPSConnection object at 0x95bb8df0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
                                            -->End of Python script error report<--
```

**Comment by volker-raschek** [comment]
Wrong repo

**Comment by shixu** [comment]
how did you solve it? i was running the plugin on my vero 4k+ (osmc) and all of a sudden it stopped working
